/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/koordinator-sh/koordinator/apis/analysis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCheckpoints implements CheckpointInterface
type FakeCheckpoints struct {
	Fake *FakeAnalysisV1alpha1
	ns   string
}

var checkpointsResource = schema.GroupVersionResource{Group: "config.koordinator.sh", Version: "v1alpha1", Resource: "checkpoints"}

var checkpointsKind = schema.GroupVersionKind{Group: "config.koordinator.sh", Version: "v1alpha1", Kind: "Checkpoint"}

// Get takes name of the checkpoint, and returns the corresponding checkpoint object, and an error if there is any.
func (c *FakeCheckpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Checkpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(checkpointsResource, c.ns, name), &v1alpha1.Checkpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Checkpoint), err
}

// List takes label and field selectors, and returns the list of Checkpoints that match those selectors.
func (c *FakeCheckpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CheckpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(checkpointsResource, checkpointsKind, c.ns, opts), &v1alpha1.CheckpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CheckpointList{ListMeta: obj.(*v1alpha1.CheckpointList).ListMeta}
	for _, item := range obj.(*v1alpha1.CheckpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested checkpoints.
func (c *FakeCheckpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(checkpointsResource, c.ns, opts))

}

// Create takes the representation of a checkpoint and creates it.  Returns the server's representation of the checkpoint, and an error, if there is any.
func (c *FakeCheckpoints) Create(ctx context.Context, checkpoint *v1alpha1.Checkpoint, opts v1.CreateOptions) (result *v1alpha1.Checkpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(checkpointsResource, c.ns, checkpoint), &v1alpha1.Checkpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Checkpoint), err
}

// Update takes the representation of a checkpoint and updates it. Returns the server's representation of the checkpoint, and an error, if there is any.
func (c *FakeCheckpoints) Update(ctx context.Context, checkpoint *v1alpha1.Checkpoint, opts v1.UpdateOptions) (result *v1alpha1.Checkpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(checkpointsResource, c.ns, checkpoint), &v1alpha1.Checkpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Checkpoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCheckpoints) UpdateStatus(ctx context.Context, checkpoint *v1alpha1.Checkpoint, opts v1.UpdateOptions) (*v1alpha1.Checkpoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(checkpointsResource, "status", c.ns, checkpoint), &v1alpha1.Checkpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Checkpoint), err
}

// Delete takes name of the checkpoint and deletes it. Returns an error if one occurs.
func (c *FakeCheckpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(checkpointsResource, c.ns, name, opts), &v1alpha1.Checkpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCheckpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(checkpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CheckpointList{})
	return err
}

// Patch applies the patch and returns the patched checkpoint.
func (c *FakeCheckpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Checkpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(checkpointsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Checkpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Checkpoint), err
}
